rootProject.name = 'vader'

include ':services:core:java:core-belief-state-generator-service'
include ':services:core:java:core-communication-service'
include ':services:core:java:core-flow-service'

include ':services:util:python:util-simulation-service'
include ':services:util:ts:util-ubiquia-dashboard'

include ':services:test:java:test-belief-state-generator-service'
include ':services:test:java:test-flow-service'

include ':services:dag:workbench:python:dag-workbench-whisperer'
include ':services:dag:workbench:python:dag-workbench-scaffold'
include ':services:dag:workbench:ts:dag-workbench-ui'
