# Helm values for the "dev" Vader deployment configuration.
logging:
  vader: DEBUG

vader:
  mode: DEV
  components:
    core:
      coreServer:
        image:
          registry: docker.io/jeremyacase
          repository: vader-core-server
          tag: latest
      coreUi:
        image:
          registry: docker.io/jeremyacase
          repository: vader-core-ui
          tag: latest

infrastructure:
  image:
    pullPolicy: IfNotPresent

telemetry:
  prometheus:
    enabled: false
