# Helm values for the "dev" Vader deployment configuration.
logging:
  vader: DEBUG

vader:
  mode: DEV
  database:
    type: HSQL
  components:
    core:
      coreServer:
        image:
          registry: docker.io/vader
          repository: core-server
          tag: latest

infrastructure:
  image:
    pullPolicy: Never

telemetry:
  prometheus:
    enabled: false
