apiVersion: v1
kind: ConfigMap
metadata:
  name: vader-core-server-config
data:
  application.yaml: |

    logging:
      level:
        org.vader: {{ .Values.logging.vader }}

    management:
      endpoint:
        info:
          enabled: true
          java:
            enabled: true
          build:
            enabled: true
        health:
          probes:
            enabled: true
          show-components: always
          show-details: always
        prometheus:
          enabled: {{ .Values.telemetry.prometheus.enabled }}
      endpoints:
        web:
          exposure:
            include: info, health{{- if .Values.telemetry.prometheus.enabled }}, prometheus{{- end }}
      metrics:
        tags:
          application: ${spring.application.name}

    spring:
      server:
        port: {{ .Values.convenience.variables.spring.port }}

      application:
        name: core-server

      datasource:
        {{- if eq .Values.vader.database.type "HSQL" }}
        driverClassName: org.hsqldb.jdbc.JDBCDriver
        url: jdbc:hsqldb:mem:vaderDb;sql.syntax_pgs=true
        username: SA
        password: ""
        {{- end }}
        hikari:
          transaction-isolation: {{ .Values.vader.database.transactionIsolation }}
      jpa:
        hibernate:
          ddl-auto: {{ .Values.vader.database.ddlAutoSetting }}
        properties:
          hibernate:
            generate_statistics: false
            format_sql: true

    vader:
      mode: {{ .Values.vader.mode | default "PROD" }}
