apiVersion: v1
kind: ConfigMap
metadata:
  name: vader-core-server-config
data:
  application.yaml: |

    logging:
      level:
        org.vader: {{ .Values.logging.vader }}

    management:
      endpoint:
        info:
          enabled: true
          java:
            enabled: true
          build:
            enabled: true
        health:
          probes:
            enabled: true
          show-components: always
          show-details: always
        prometheus:
          enabled: {{ .Values.telemetry.prometheus.enabled }}
      endpoints:
        web:
          exposure:
            include: info, health{{- if .Values.telemetry.prometheus.enabled }}, prometheus{{- end }}
      metrics:
        tags:
          application: ${spring.application.name}

    spring:
      server:
        port: {{ .Values.convenience.variables.spring.port }}

      application:
        name: core-server

      datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:vaderDb;DB_CLOSE_DELAY=-1
        username: sa
        password: ""
        hikari:
          transaction-isolation: {{ .Values.vader.database.transactionIsolation }}
      jpa:
        hibernate:
          ddl-auto: {{ .Values.vader.database.ddlAutoSetting }}
        properties:
          hibernate:
            generate_statistics: false
            format_sql: true
      h2:
        console:
          enabled: true
          path: /h2-console

    vader:
      mode: {{ .Values.vader.mode | default "PROD" }}
      orchestrator:
        type: {{ .Values.vader.orchestrator.type | default "local" }}
        {{- if eq .Values.vader.orchestrator.type "local" }}
        local:
          base-url: http://vader-ollama:{{ .Values.vader.components.core.ollama.service.port }}
          model: {{ .Values.vader.orchestrator.local.model }}
        {{- end }}
