apiVersion: v1
kind: Service
metadata:
  name: vader-core-server
  labels:
    component: vader-core-server
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.convenience.variables.spring.port }}
      targetPort: http
      protocol: TCP
      nodePort: 30080
  selector:
    component: vader-core-server
